regCenter:
  serverList: localhost:6181
  namespace: elastic-job-lite-springboot
simpleJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
spring:
  datasource:
    name: kobe
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver